name: Lint Commit Messages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commitlint:
    name: Check Commit Message Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
