name: Automated Release

on:
  push:
    branches: [main, master]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Process Next Release
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Add timeout for safety

    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        # with:
        #   token: ${{ secrets.RELEASE_SECRET }}
