name: Automated Release

on:
  push:
    branches: [main, master]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Process Next Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_SECRET }}

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  # Only run this job when a release is created
  build-and-upload:
    name: Build and Upload Go Binary
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Build Go application for Linux
        env:
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: |
          # Extract version from tag 
          VERSION=${TAG_NAME}

          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.Version=$VERSION" -o "ai-commit-linux-amd64-$VERSION" ./

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ai-commit-*
          tag_name: ${{ needs.release-please.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
