name: Go Vulnerability Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  govulncheck:
    name: Scan Go Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Run vulnerability scanner
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.24.2' # Ensure consistent Go version

